# Containerization

## Introduction

A common problem observed during data analysis includes packages/libraries that are not compatible with specific R/Python software. Other times different project use specific versions of packages and the underlying R/Python versions. This leads to "dependency hell" which can be easily solved using virtual environments. A virtual environment is common to isolate the dependency requirements for specific projects which may rely on a specific R/Python version as well as specific versions of the software libraries.

### R

renv, packrat

### Python

Conda is useful package manager and can create virtual environments for pretty much anay programming language ^[https://docs.conda.io/en/latest/]. 

### Create a virtual environment
* [install conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/)
* check conda version using: ```conda --version```

#### with default python version

```{bash eval=FALSE}
conda create --name env1
conda activate env1
python --version
```

#### a specifc python version

```{bash eval=FALSE}
conda create --name env2 python=3.7
conda activate env2
python --version
```

### install packages

```{bash eval=FALSE}
conda install numpy
```

### exit virtual environment

```{bash eval=FALSE}
conda deactivate
```

## List all virtual environments

```{bash eval=FALSE}
conda env list
```

## Delete virtual environment

```{bash eval=FALSE}
conda env remove -n env1
conda env remove -n env2
```


Similar to how shipping containers carry material goods in an enclosed space, software containers consist of application related goods (*e.g.* files and dependencies) in an enclosed environment. Containerization ensure reproducibility by bundling the necessary resources required to run a given set of analyses, web application, pipelines *etc.* irrespective of the operation system (OS). Thus, containers can be run on any OS (*e.g.* Mac, Windows, Linux)^[ https://stackoverflow.com/questions/50974960/whats-the-difference-between-docker-and-python-virtualenv].


Docker references
1. [Understanding Docker Build Args, Environment Variables and Docker Compose Variables](https://vsupalov.com/docker-env-vars/)
3. [env file](https://vsupalov.com/docker-arg-env-variable-guide/)


e.g. [dockerized pipeline](https://github.com/cmap/dockerized_mts)

## Advanced
